
version: 2

models/AggregationLayer:
  - name: TeamActions
    description: "An attribute value pair table of all types of actions by team and time"
    columns:
      - name: teamid
        description: "The primary key for this table"
        tests:

  - name: SubscriptionsProd
    description: "The base table for subscriptions"
    columns:
      - name: teamid
        description: "The primary key for this table"
        tests:

models/SemanticLayer:
  - name: RenewalRates
    description: "Renewal Rates by Sport"
    columns:
      - name: sport
        description: "The primary key for this table"
        tests:

  - name: SubscriptionTermUsage
    description: "The base table for subscriptions"
    columns:
      - name: teamid
        description: "The primary key for this table"
        tests:

  - name: TeamActionsView
    description: "All actions over time a team has performed"
    columns:
      - name: teamid
        description: "The primary key for this table"
        tests: