version: 2

sources:
  - name: PostgresPersonal
    database: defaultdb
    quoting:
      database: false
      schema: false
      identifier: false
    tables:
      - name: teams
      - name: uploads
      - name: views
      - name: subscriptions
      - name: highlights