
version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: TotalHighlights
    description: "A calculation of the total highlights by team"
    columns:
      - name: authuser
        description: "The primary key for this table"
        tests:
          - not_null

  - name: Subscriptions
      description: "A calculation of the total highlights by team"
      columns:
        - name: teamid
          description: "The primary key for this table"
          tests:
            - not_null
